### ISSUE TITLE
Does not work in perl 5.24

### ISSUE THREAD

**Issue by AndrewSav** [quartata/pl-lang#1]
Perl 5.24 [removes a bunch of experimental features](http://stackoverflow.com/a/41192741/284111), which this project seems to use.

I'm getting the following output:

```
given is experimental at /opt/pl-lang/pl.pl line 92.
Experimental pop on scalar is now forbidden at /opt/pl-lang/pl.pl line 25, near "%2;"
Type of arg 1 to List::Util::reduce must be block or sub {} (not reference constructor) at /opt/pl-lang/pl.pl line 197, near "pop)"
Type of arg 1 to List::Util::reduce must be block or sub {} (not reference constructor) at /opt/pl-lang/pl.pl line 219, near "@_)"
Execution of /opt/pl-lang/pl.pl aborted due to compilation errors.
```

**Comment by quartata** [comment]
I'm not entirely sure why that error is happening since I'm not popping from a scalar (at least I shouldn't be).  The reduce error doesn't make any sense either, I'll try to obtain 5.24 and see what's going on.

**Comment by AndrewSav** [comment]
@quartata [This](https://github.com/TryItOnline/pl-lang/commit/45ab4a0940fa3ec19d941292489375fed1d28935) fixed the issue (all the issues) for me, unfortunately I do not know perl *at all*, so I have no idea if it's even correct.

**Comment by quartata** [comment]
New commit should fix this (hopefully).
